name: 'FPL H2H Standings'
description: 'Generate FPL H2H quarter standings in ./data/fpl-h2h-standings.yaml'
runs:
  using: 'docker'
  image: '../../../Dockerfile'
  args:
    - python3
    - scripts/fpl_h2h_standings.py
    - -l
    - 571225
    - -o
    - ./data/fpl-h2h-standings.yaml
    - -v
