# The URL to the root of the website
baseURL = "https://jeremic.ca/"

# This value determines the default language of theme components and content
defaultContentLanguage = "en"

# When enabled a robots.txt file will be created in the site root that allows search engines to crawl the entire site
enableRobotsTXT = true

# The number of articles listed on each page of the article listing
paginate = 10

# The number of words that are used to generate the article summary when one is not provided in the front matter. A value of 0 will use the first sentence.
summaryLength = 0

[outputs]
  # The output formats that are generated for the site. Congo requires HTML, RSS and JSON for all theme components to work correctly
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  # Override default Hugo taxonomies
  tag = "tags"

[frontmatter]
  # Fetches the date from the content file's filename
  date = [':filename', ':default']