[[main]]
  name = "About"
  url = "/about"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 30

[[footer]]
  name = "Contact"
  url = "/about/#contact"
  weight = 10

[[footer]]
  name = "Tags"
  url = "/tags"
  weight = 20