main:
  - name: About
    url: /about
    weight: 10
  - name: Projects
    url: /projects
    weight: 20
  - name: Blog
    url: /blog
    weight: 30

footer:
  - name: Contact
    url: /about/#contact
    weight: 10
  - name: Tags
    url: /tags
    weight: 20
