url: http://jeremic.ca

# Global website configuration
website:
  author:
    name: Filip Jeremic
    email: filip@jeremic.ca
    title: Compiler Developer
    github: https://github.com/fjeremic
    linkedin: https://www.linkedin.com/in/filip-jeremic-11807b18b
  background: assets/images/profile/background.jpg
  description: jeremic.ca
  disqus: "jeremic"

# Where things are
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  fpl:
    output: true
    permalink: /:collection/:path/

# Handling reading
exclude:
  - .asset-cache/
  - .git/
  - .sass-cache/
  - .editorconfig
  - .gitignore
  - assets/scss/*
  - assets/plugins/**/*.scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - Filip-Jeremic-Resume.aux
  - Filip-Jeremic-Resume.log
  - Filip-Jeremic-Resume.tex
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - res.cls

# Plugin configurations
plugins:
  - jekyll-category-pages
  - jekyll-paginate
  - jekyll-tidy

# Plugin configuration for jekyll-category-pages
category_layout: category.html

# Plugin configuration for jekyll-tidy
jekyll_tidy:
  compress_html: false

# Markdown Processors
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

# Tabler configuration
colors:
  blue:
    hex: '#467fcf'
    name: Blue
  azure:
    hex: '#45aaf2'
    name: Azure
  indigo:
    hex: '#6574cd'
    name: Indigo
  purple:
    hex: '#a55eea'
    name: Purple
  pink:
    hex: '#f66d9b'
    name: Pink
  red:
    hex: '#e74c3c'
    name: Red
  orange:
    hex: '#fd9644'
    name: Orange
  yellow:
    hex: '#f1c40f'
    name: Yellow
  lime:
    hex: '#7bd235'
    name: Lime
  green:
    hex: '#5eba00'
    name: Green
  teal:
    hex: '#2bcbba'
    name: Teal
  cyan:
    hex: '#17a2b8'
    name: Cyan
  gray:
    hex: '#868e96'
    name: Gray
  gray-dark:
    hex: '#343a40'
    name: Dark gray

theme-colors:
  primary:
    hex: '#467fcf'
    name: Primary
  secondary:
    hex: '#868e96'
    name: Secondary
  success:
    hex: '#38c172'
    name: Success
  info:
    hex: '#17a2b8'
    name: Info
  warning:
    hex: '#f8b700'
    name: Warning
  danger:
    hex: '#f90049'
    name: Danger

theme-plugins:
  datatables:
    name: Datatables
    files: [js]